# Generated by Django 4.2.26 on 2025-11-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='new_field',
            field=models.SlugField(default='About Me content'),
            preserve_default=False,
        ),
    ]
